In [0]:
import torch

In [0]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

In [3]:
print(x*y)

tensor([3, 8])


In [4]:
x = torch.zeros([3,4])
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([3, 4])

In [6]:
y = torch.rand([4,8])
print(y)

tensor([[0.9544, 0.0342, 0.6851, 0.5822, 0.7935, 0.4456, 0.1526, 0.8647],
        [0.6902, 0.0097, 0.2952, 0.1352, 0.0959, 0.5416, 0.0672, 0.4175],
        [0.6413, 0.9672, 0.8147, 0.9910, 0.4149, 0.8251, 0.1746, 0.1744],
        [0.4711, 0.3098, 0.4967, 0.3206, 0.8353, 0.2429, 0.7968, 0.3986]])


In [8]:
y = y.view([4,8])
print(y)

tensor([[0.9544, 0.0342, 0.6851, 0.5822, 0.7935, 0.4456, 0.1526, 0.8647],
        [0.6902, 0.0097, 0.2952, 0.1352, 0.0959, 0.5416, 0.0672, 0.4175],
        [0.6413, 0.9672, 0.8147, 0.9910, 0.4149, 0.8251, 0.1746, 0.1744],
        [0.4711, 0.3098, 0.4967, 0.3206, 0.8353, 0.2429, 0.7968, 0.3986]])


In [9]:
y.view([2,16])

tensor([[0.9544, 0.0342, 0.6851, 0.5822, 0.7935, 0.4456, 0.1526, 0.8647, 0.6902,
         0.0097, 0.2952, 0.1352, 0.0959, 0.5416, 0.0672, 0.4175],
        [0.6413, 0.9672, 0.8147, 0.9910, 0.4149, 0.8251, 0.1746, 0.1744, 0.4711,
         0.3098, 0.4967, 0.3206, 0.8353, 0.2429, 0.7968, 0.3986]])

In [10]:
print(y)

tensor([[0.9544, 0.0342, 0.6851, 0.5822, 0.7935, 0.4456, 0.1526, 0.8647],
        [0.6902, 0.0097, 0.2952, 0.1352, 0.0959, 0.5416, 0.0672, 0.4175],
        [0.6413, 0.9672, 0.8147, 0.9910, 0.4149, 0.8251, 0.1746, 0.1744],
        [0.4711, 0.3098, 0.4967, 0.3206, 0.8353, 0.2429, 0.7968, 0.3986]])


In [11]:
y = y.view([2,16])
print(y)

tensor([[0.9544, 0.0342, 0.6851, 0.5822, 0.7935, 0.4456, 0.1526, 0.8647, 0.6902,
         0.0097, 0.2952, 0.1352, 0.0959, 0.5416, 0.0672, 0.4175],
        [0.6413, 0.9672, 0.8147, 0.9910, 0.4149, 0.8251, 0.1746, 0.1744, 0.4711,
         0.3098, 0.4967, 0.3206, 0.8353, 0.2429, 0.7968, 0.3986]])


In [15]:
torch.randn([2,4])

tensor([[ 0.3543, -0.3802,  2.0222, -0.3555],
        [ 1.0480,  0.5094, -1.8351, -2.2779]])